# Generated by Django 6.0.2 on 2026-02-25 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=50)),
                ('reference_code', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('pin_code', models.CharField(max_length=10)),
                ('dob', models.DateField(default='2000-01-01')),
                ('notified', models.BooleanField(default=False)),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayslipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('year', models.IntegerField()),
                ('months', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayslipRetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('months', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('request_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Admin Login'), ('logout', 'Admin Logout'), ('login_failed', 'Failed Login Attempt'), ('approve_request', 'Approved Request'), ('reject_request', 'Rejected Request'), ('delete_request', 'Deleted Request'), ('upload_payslip', 'Uploaded Payslip'), ('mark_completed', 'Marked Completed'), ('delete_log', 'Deleted Retrieval Log'), ('view_logs', 'Viewed Retrieval Logs'), ('export_reports', 'Exported Reports')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslip_app_adminauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('ministry', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_payslip',
                'unique_together': {('nin', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayslipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='payslips/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_files', to='payslip_app.paysliprequest')),
            ],
        ),
    ]
